src/main/java/psweb/hangman/HangmanBean.java
package psweb.hangman;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;

import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.PropertySource;
import org.springframework.core.io.ClassPathResource;
import org.springframework.core.io.Resource;
import org.springframework.stereotype.Component;

@Component
@ManagedBean
@SessionScoped
@Configuration
@PropertySource("classpath:resource/hangman.properties")
public class HangmanBean extends _Bean
{    
	//
	// Atributos
	//
	private Hangman hangman;
	//private List<Word> listEasyWords = new ArrayList<>();
	//private List<Word> listMediumWords = new ArrayList<>();
	//private List<Word> listHardWords = new ArrayList<>();
	private List<String> hangmanImageList = new ArrayList<>();
	
	//Audio player
	AudioPlayer player = new AudioPlayer();
	
	//
	// Campos do Formulário
	//
	private String letter = "";
	private String difficult = "";
	private String hangmanImage = "";
	//
	// Construtor
	//
	public HangmanBean()
	{
		this.hangman = new Hangman();
		this.difficult = "Medium";
		this.loadImages();
		//The first image is int the last index
		this.hangmanImage = this.hangmanImageList.get(hangmanImageList.size() - 1);
		//The default difficult is medium, so we reset with the list of medium words
		this.hangman.reset(this.getMediumListWord());
		
	}
	
	//
	// Operações
	//
	public void guess() throws IOException
	{
		char chr = letter.toCharArray()[0];
		hangman.input(chr);
		this.hangmanImage = this.getHangmanImageList().get(getChances());
		if(this.isGameLose()){
			//get audio from resource path
			player.playSound(getClass().getClassLoader().getResource("choque.wav").getPath());
		}
		letter = "";
	}
	
	public void reset()
	{
		letter = "";
		if(this.difficult.equals("Easy")) {
			this.hangman.reset(this.getEasyListWord());
		}else if(this.difficult.equals("Medium")) {
			this.hangman.reset(this.getMediumListWord());
		}else {
			this.hangman.reset(this.getHardListWord());
		}
		this.hangmanImage = this.hangmanImageList.get(hangmanImageList.size() - 1);
		
	}
	
	//
	// Métodos de Acesso
	//
	public String getWord()
	{
		return hangman.getWordAsString();
	}
	
	public String getAnswerAsString() {
		return hangman.getAnswerAsString();
	}
	
	public Integer getChances()
	{
		return hangman.getChances();
	}
	
	public String getAttempts()
	{
		return hangman.getInputHistory().toString();
	}
	
	public boolean isGameOver()
	{
		return hangman.isGameOver();
	}
	
	public boolean isGameWin()
	{
		return hangman.isComplete();
	}
	
	public boolean isGameLose()
	{
		return hangman.getChances()==0;
	}
	
	public String getLetter() {
		return letter;
	}
	
	public void setLetter(String letter) {
		this.letter = letter;
	}
	
	public String getDifficult() {
		return difficult;
	}

	public void setDifficult(String difficult) {
		this.difficult = difficult;
	}

	public List<String> getHangmanImageList() {
		return hangmanImageList;
	}

	public void setHangmanImageList(List<String> hangmanImageList) {
		this.hangmanImageList = hangmanImageList;
	}
	
	public void loadImages() {
		for(int i = 0 ; i < 7 ; i++) {
			this.getHangmanImageList().add("images\\hangman" + i + ".png");
		}
	}

	public String getHangmanImage() {
		return hangmanImage;
	}

	public void setHangmanImage(String hangmanImage) {
		this.hangmanImage = hangmanImage;
	}
}  

src/main/java/psweb/hangman/_Bean.java
package psweb.hangman;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Properties;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.servlet.ServletContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.PropertySource;
@Configuration

public abstract class _Bean 
{
	private String dicFolder;
	
	private List<Word> listEasyWords = new ArrayList<>();
	private List<Word> listMediumWords = new ArrayList<>();
	private List<Word> listHardWords = new ArrayList<>();
	
	public _Bean() {
		String line = "";
		Locale.setDefault(new Locale("pt","BR"));
		try {
			
			InputStream input= new FileInputStream(getClass().getClassLoader().getResource("dicionario.dic").getPath());
			BufferedReader reader = new BufferedReader(new InputStreamReader(input));
			
			while((line = reader.readLine()) != null) {
				String[] splitWord = line.split("/");
				//TODO change if to Stream API 
				if(splitWord[0].length() < 5) {
					listEasyWords.add(new Word(splitWord[0]));
				}else if(splitWord[0].length() > 5 && splitWord[0].length() < 7) {
					listMediumWords.add(new Word(splitWord[0]));
				}else if(splitWord[0].length() > 7) {
					listHardWords.add(new Word(splitWord[0]));
				}
			}
			
			reader.close();
			
		} catch (IOException e) {
			e.printStackTrace();
		}
		
	}
	
	public Object getJsfParam(String param){
		return getHttpServletRequest().getAttribute(param);
	}
	
	public HttpServletRequest getHttpServletRequest(){
		return (HttpServletRequest)getExternalContext().getRequest();
	}
	
	public HttpServletResponse getHttpServletResponse() {
		return (HttpServletResponse)getExternalContext().getResponse();
	}
	
	public HttpSession getHttpSession(){
		return getHttpServletRequest().getSession();
	}	
	
	public ExternalContext getExternalContext(){
		return getFacesContext().getExternalContext();
	}
	
	public ServletContext getServletContext(){
		return (ServletContext)getExternalContext().getContext();
	}
	
	public String getFileSeparator(){
		return System.getProperty("file.separator");
	}
	
	public FacesContext getFacesContext(){
		return FacesContext.getCurrentInstance();
	}
	
	public List<Word> getEasyListWord() {
		return this.listEasyWords;
	}
	
	public List<Word> getMediumListWord() {
		return this.listMediumWords;
	}
	
	public List<Word> getHardListWord() {
		return this.listHardWords;
	}
}

src/main/webapp/hangman.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<f:view contentType="text/html">
		<h:head>						
			<script src="js/geral.js"></script>	
		</h:head>
	
		<h:body>
			<h:form id="form">
				<h1>The PSWEB Hangman</h1> 
				<hr/>	
				<h2>Word: <h:outputText value="#{hangmanBean.word}" /> <p:graphicImage value ="#{hangmanBean.hangmanImage}"/></h2>
				<br/>
				<h2>Chances: <h:outputText value="#{hangmanBean.chances}" /></h2>
				<br/>
				<h2>Attempts: <h:outputText value="#{hangmanBean.attempts}" /></h2>
				<br/>			
				Pick a Letter: <p:inputText value="#{hangmanBean.letter}" 
				                            maxlength="1"
				                            readonly="#{hangmanBean.gameOver}">
									<p:ajax event="keyup" update="form" />
							   </p:inputText>
				<p:commandButton value="Guess" 
				                 actionListener="#{hangmanBean.guess()}"
				                 disabled="#{empty hangmanBean.letter or hangmanBean.gameOver}"
				                 icon="ui-icon-check"
				                 update="form"/>
				<p:commandButton value="Reset" 
								 icon="fa fa-refresh"
				                 actionListener="#{hangmanBean.reset()}"
				                 update="form"/>		
				
				<ui:fragment rendered="#{hangmanBean.gameOver}">
					<hr/> 
					<h1>				
						<h:outputText value="Congratulations, you guessed!" 
									  rendered="#{hangmanBean.gameWin}"/>
						<h:outputText value="You are dead, hanged dead... the correct answer is: #{hangmanBean.answerAsString}"  
						              rendered="#{hangmanBean.gameLose}"/>
					</h1>
				</ui:fragment>					
			</h:form>
			<h:form id="formDifficult">
			Choose a Difficult: <p:outputLabel for="difficult" />
			   <p:selectOneRadio id="difficult" value="#{hangmanBean.difficult}">
		            <f:selectItem itemLabel="Easy" itemValue="Easy" icon = "fa-font"/>
		            <f:selectItem itemLabel="Medium" itemValue="Medium" />
		            <f:selectItem itemLabel="Hard" itemValue="Hard" />
		        </p:selectOneRadio>			
		        		 Set the Difficult:<p:commandButton value="Set" 
							     actionListener="#{hangmanBean.reset()}"
							     icon="ui-icon-check"
				                 update="formDifficult form"
				                 />		
		        </h:form>			
		</h:body>
	</f:view>
</html>